/**
* This is an autogenerated file created by the Stencil compiler.
* It contains typing information for all components that exist in this project.
*/
/* tslint:disable */

import '@stencil/core';




export namespace Components {

  interface WcDatepicker {
    'value': string;
  }
  interface WcDatepickerAttributes extends StencilHTMLAttributes {
    'value'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'WcDatepicker': Components.WcDatepicker;
  }

  interface StencilIntrinsicElements {
    'wc-datepicker': Components.WcDatepickerAttributes;
  }


  interface HTMLWcDatepickerElement extends Components.WcDatepicker, HTMLStencilElement {}
  var HTMLWcDatepickerElement: {
    prototype: HTMLWcDatepickerElement;
    new (): HTMLWcDatepickerElement;
  };

  interface HTMLElementTagNameMap {
    'wc-datepicker': HTMLWcDatepickerElement
  }

  interface ElementTagNameMap {
    'wc-datepicker': HTMLWcDatepickerElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
